### ISSUE TITLE
在某种情况下会报错

### ISSUE THREAD

**Issue by gdft2112** [mstxq17/MoreFind#2]
如图
<img width="1250" alt="image" src="https://user-images.githubusercontent.com/37747628/200277966-40b9691a-2346-41f1-b244-b1097ec6dbbe.png">

**Comment by mstxq17** [comment]
> 如图 <img alt="image" width="1250" src="https://user-images.githubusercontent.com/37747628/200277966-40b9691a-2346-41f1-b244-b1097ec6dbbe.png">

这个看起来是在ubuntu环境，辛苦粘贴写具体URL和命令，并且通过执行MoreFind version 打印出版本，这样能够让我快速排查出问题并进行修复，感谢您的反馈！
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/29624427/202886309-d4de0bae-09e3-4c99-aef6-e3ce8ba69402.png">

**Comment by mstxq17** [comment]
OK,找到问题所在了，多了一个%，会在下一个版本进行处理，兼容这个异常。
<img width="1499" alt="image" src="https://user-images.githubusercontent.com/29624427/202886412-d38f0805-ea55-4c25-8913-e136d8856281.png">

**Comment by mstxq17** [comment]
hello，v1.2.7版本已经修复该问题，`go install  github.com/mstxq17/MoreFind@v1.2.7` 可以通过该命令更新你的版本哦。
